### ISSUE TITLE
parent Sdb* pointer for SdbCallback

### ISSUE THREAD

**Issue by XVilka** [radareorg/sdb#148]
To be able to pass something more than just parent sdb, or struct containing it in sdb_foreach() in userdata pointer.

**Comment by radare** [comment]
just pass this into the void* arg, for callback patterns it is better to only pass 1 argument, most projects do it like this for simplicity and consistency

**Comment by XVilka** [comment]
This is what I did - I passed RAnal, which contains a link to the parent SDB, also some other useful stuff, but still.

**Comment by radare** [comment]
Yeah i understand your frustation :D
