### ISSUE TITLE
Switch to GitHub Actions and SourceHut

### ISSUE THREAD

**Issue by XVilka** [radareorg/sdb#213]
- GitHub Action for Linux, Windows, OS X
- SourceHut for *BSDs
- Maybe make Travis for ARM, PPC, S390 like in radare2

**Comment by XVilka** [comment]
Travis-CI.org will shutdown at December 31, 2020: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D

**Comment by XVilka** [comment]
It is required for reviving Coverity Scan https://scan.coverity.com/projects/1651 (Last analyzed: Dec 24, 2018)

**Comment by trufae** [comment]
Done
