### ISSUE TITLE
About latest release

### ISSUE THREAD

**Issue by chenrui333** [radareorg/sdb#243]
It looks like the 1.8.2 release did not get marked latest release or pre-release, so raising this issue to double check on it. Thanks.

Relates to https://github.com/Homebrew/homebrew-core/pull/85491

**Comment by trufae** [comment]
Oh! thanks for the heads up. fixed and pushed 1.8.3

**Comment by chenrui333** [comment]
@trufae 👋 looks like the release build got stuck again, https://github.com/radareorg/sdb/actions/runs/5415183426/jobs/9843242971

relates to https://github.com/Homebrew/homebrew-core/pull/135395

**Comment by chenrui333** [comment]
just raised [a separate issue](https://github.com/radareorg/sdb/issues/269) instead.
