### ISSUE TITLE
Can I use sdb with Python

### ISSUE THREAD

**Issue by ilker610** [radareorg/sdb#254]
I'm a Python developer but I need some answers.

1) Can I use sdb ?

2) sdb has a any Python module ?

**Comment by trufae** [comment]
Sorry for the late response. Yes, you can use SDB, but the bindings I wrote are based on CTypes and only work with Python2. i have massaged the autogenerated script to work with Python3, but it's still ugly and the module is not published to pip.

I am happy to make proper native python3 bindings and publish the module in pypi.

The API is quite simple and should be quite straight forward. Also, if you care about performance, using ctypes is probably not the best solution, so im thinking in writing the new syntactic-sugar bindings in plain C.

How does it sound?

**Comment by trufae** [comment]
Done. I wrote a native module and publish it, for now it's just covering very few basic methods of sdb. but will add more commits to support the whole API as well as document the methods. Help and contribts are welcome to speedup this :)

```
pip install r2sdb
```
