### ISSUE TITLE
1.9.8 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [radareorg/sdb#269]
👋 it looks like [the release action run](https://github.com/radareorg/sdb/actions/runs/5415183426/jobs/9843242971) did not complete successfully, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/135395

**Comment by trufae** [comment]
i think we can close this ticket, but i plan to cut a new release of sdb soon
