### ISSUE TITLE
2.0.1 release did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [radareorg/sdb#284]
👋 just heads up that 2.0.1 release did not get marked as latest release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/183056

**Comment by trufae** [comment]
Thanks for the heads up :) i need to automate the machinery in the ci https://github.com/radareorg/sdb/releases/tag/2.0.1

**Comment by chenrui333** [comment]
yeah, totally, thanks for the quick turnaround.
