### ISSUE TITLE
SDB failed to create files in the Windows from the MIngw32 shell

### ISSUE THREAD

**Issue by XVilka** [radareorg/sdb#75]
SDB failed to create files in the Windows from the MIngw32 shell

```
a.kochkov@WS-ANTON ~/radare/radare2/libr/syscall/d
$ /bin/sh gen.sh < dos-x86-16 | ../../../libr/../shlr/sdb/sdb dos-x86-16.sdb =
sdb: Cannot open 'dos-x86-16.sdb.tmp' for writing.
Cannot create database
a.kochkov@WS-ANTON ~/radare/radare2/libr/syscall/d
```

Original error from the radare2 building process

```
make[3]: Entering directory `/d/Work/radare/radare2/libr/syscall'
make -C d
make[4]: Entering directory `/d/Work/radare/radare2/libr/syscall/d'
make[5]: Entering directory `/d/Work/radare/radare2/libr/syscall/d'
rm -f dos-x86-16.sdb
/bin/sh gen.sh < dos-x86-16 | ../../../libr/../shlr/sdb/sdb dos-x86-16.sdb =
make[5]: *** [dos-x86-16.sdb] Error 116
make[5]: Leaving directory `/d/Work/radare/radare2/libr/syscall/d'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/d/Work/radare/radare2/libr/syscall/d'
make[3]: *** [do] Error 2
```

**Comment by radare** [comment]
works for me on wine. this is very important, so let me know how can i reproduce this from linux/osx

**Comment by XVilka** [comment]
@radare so this is the regression https://github.com/radare/radare2/issues/1582

**Comment by XVilka** [comment]
Was fixed in this commit https://github.com/radare/sdb/commit/874e92a4f8b89df8d33a4162fe6eb7a3e787e0d6

**Comment by XVilka** [comment]
This time though the reason is another (still trying to find out).

**Comment by radare** [comment]
Cc @skuater

**Comment by XVilka** [comment]
@radare @skuater - any ideas how to fix this? This prevents from building radare2 on mingw32 on some windows systems.

**Comment by radare** [comment]
can anyone reproduce? :)

**Comment by XVilka** [comment]
I can provide the failing binary

**Comment by XVilka** [comment]
Here it is http://xvilka.me/sdb.exe

**Comment by radare** [comment]
Can u share build logs and compiler version/etc? Can you reproduce the same issue by building sdb from git instead of building yhe one shipped in r2?

**Comment by XVilka** [comment]
Yes, I can reproduce this on vanilla sdb.

**Comment by radare** [comment]
then i would suggest focusing/fixing the issue on vanila sdb rather than in sdb.

tell me how to reproduce

**Comment by XVilka** [comment]
http://paste.kolibrios.org/raw/m0abZBm955GrFUkSqGFF/ - build log.
Just copy gen.sh and any syscall file in sdb and call same command as r2 makefile:
` /bin/sh gen.sh < dos-x86-16 | sdb dos-x86-16.sdb =`

**Comment by XVilka** [comment]
it returns the same error: https://github.com/radare/radare2/issues/1582#issuecomment-60931631

**Comment by radare** [comment]
Sdb's main is still buggy, i will rework it and push the update into r2 asap. Please confirm if latest sdb works as expected for you. We need more tests for sdb :) to verify db is always created

**Comment by XVilka** [comment]
```
gcc -c  -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -std=c99  -Wall -g -MMD -D
MINGW32=1 -I../src -g -ggdb  -o main.o main.c
In file included from main.c:4:0:
mcsdb.h:43:16: error: array type has incomplete element type
main.c: In function 'fds_add':
main.c:29:22: error: 'POLLIN' undeclared (first use in this function)
main.c:29:22: note: each undeclared identifier is reported only once for each fu
nction it appears in
main.c:29:31: error: 'POLLHUP' undeclared (first use in this function)
main.c:29:41: error: 'POLLERR' undeclared (first use in this function)
main.c: In function 'fds_server':
main.c:152:22: error: 'POLLIN' undeclared (first use in this function)
main.c: In function 'net_loop':
main.c:260:23: error: 'POLLIN' undeclared (first use in this function)
main.c:267:3: warning: implicit declaration of function 'poll' [-Wimplicit-funct
ion-declaration]
main.c:310:29: error: 'POLLHUP' undeclared (first use in this function)
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/d/Work/radare/sdb/memcache'
make: *** [all] Error 2
```

**Comment by radare** [comment]
Not sure how are you building, but it loks like itsmissing some flags, see `make w32`. also, your issue seems related to windows itself. unable to create files with 2 extensions or so

**Comment by XVilka** [comment]
@radare `touch dos-x86-16.sdb.tmp` from the same shell works perfectly

**Comment by radare** [comment]
can you check with latest git?

**Comment by XVilka** [comment]
@radare ofc i will, when i'll arrive to the right place.

**Comment by XVilka** [comment]
@radare error still persist, but now it just crashed, without any error

**Comment by XVilka** [comment]
error still here, even in the latest sdb

**Comment by radare** [comment]
I bet this is a bug in the toolchain. It works fine in all the official builds i do from my machine and i tested it building with the osx and linux toolchains. And iirc also with the native mingw i installed on win10.

Will ping @skuater to see if he can reproduce it and find a solution for this issue

**Comment by skuater** [comment]
hi , going to test it

**Comment by skuater** [comment]
Tested with last GIT repository under Windows 7 x64 SP1 under MingW32, and work without problems.

**Comment by XVilka** [comment]
Can you share the produced binary,  please?

**Comment by XVilka** [comment]
@skuater how do you built your sdb? Diaphora shows too much differences between my executable and yours. Just `make` or `make w32`?

**Comment by radare** [comment]
Xv confirmed this was a toolchain issue

**Comment by XVilka** [comment]
@skuater Ok, same problem for the MSYS2/Mingw-w64 - just compile sdb using the toolchain, described in https://github.com/radare/radare2book/blob/master/introduction/windows_compilation.md#mingw-w64

**Comment by XVilka** [comment]
@skuater @radare see the example here (Appveyor MSYS2 build) https://ci.appveyor.com/project/radare/radare2-hnku1

**Comment by radare** [comment]
This thing matters for the release. Thx

**Comment by radare** [comment]
But i would like to have the issue reproduced in sdb itself. Not the sdb embedded in r2

**Comment by 0xABD** [comment]
I can reproduce the issue with a msys2 + mingw64 toolchain on windows, set up exactly as per https://github.com/radare/radare2book/blob/master/introduction/windows_compilation.md#mingw-w64

**Comment by 0xABD** [comment]
I have built sdb separately from github rev `8a9f178`, copied the sdb.exe to the `\radare2\shlr\sdb\sdb.exe`, replacing the old one, and now I still have the same error code 127 for any of the template files in that folder when trying e.g. 
```
"/bin/sh" gen.sh < darwin-x86-64 | ../../..//libr/../shlr/sdb//sdb.exe darwin-x86-64 =
```

**Comment by 0xABD** [comment]
The crash is in the first call of `cdb_alloc_free()` at line 179 of `cdb_make.c`, called from `cdb_make_finish()`. `free()` call fails directly on the first element of linked list. 
The pointer is allocated through `_aligned_malloc()`, but freed via a normal `free()`. On MinGW we need to call `_aligned_free()` for pointers allocated via `_aligned_malloc()`.

Attaching the PR:
https://github.com/radare/sdb/pull/95

**Comment by radare** [comment]
Can we have this build generated from linux?

**Comment by radare** [comment]
Should be fixed now after merging this. i'll update the sdb version embedded in r2 and see what happens with the automated builds. thanks @0xABD !

**Comment by XVilka** [comment]
Irrelevant now.
